apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports: #add ports for mongo express
        - containerPort: 8081
        env: #add enivroment variables for username, password and url of mongoDB
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongodb-secret
            key: mongo-username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongodb-secret
            key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
           configMapKeyRef: #add configmap reference, name is configmap name, key is database_url from configmap
            name: mongodb-configmap
            key: database_url
---
apiVersion: v1
kind: Service
metadata:
 name: mongo-express-service
spec:
 selector: #the same as mongo express name
  app: mongo-express
 type: LoadBalancer #type for external service
 ports:
  - protocol: TCP
    port: 8081 #mongo express service port
    targetPort: 8081 #mongo express deployment port
    nodePort: 30000 #must be between 30000 - 32767
