apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports: #add ports for mongoDB
        - containerPort: 27017
        env: #add enviroment variables for mongoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongodb-secret #secret name
            key: mongo-username  #username value from secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongodb-secret #secret name
            key: mongo-password  #password value from secret

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector: #is using to connect to the pod, it is the same as a label name in deployment
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 #it is a service port
      targetPort: 27017 #it is a target port, so it is deployment container port
